const GET_PRODUCT = 'GET_PRODUCT';
const ADD_PRODUCTS = 'ADD_PRODUCTS';
const LOADING = 'LOADING';
const ADD_TO_SHOPPING_CARD = 'ADD_TO_SHOPPING_CARD';
const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
const CHANGE_PRICE = 'CHANGE_PRICE';
const DELETE_FROM_SHOPPING_CARD = 'DELETE_FROM_SHOPPING_CARD';
const REMOVE_PRODUCTS_FROM_BASKET = 'REMOVE_PRODUCTS_FROM_BASKET';

export default {
  GET_PRODUCT,
  ADD_PRODUCTS,
  LOADING,
  ADD_TO_SHOPPING_CARD,
  CHANGE_QUANTITY,
  CHANGE_PRICE,
  DELETE_FROM_SHOPPING_CARD,
  REMOVE_PRODUCTS_FROM_BASKET,
};
