const GET_PRODUCT = 'GET_PRODUCT';
const ADD_PRODUCTS = 'ADD_PRODUCTS';
const LOADING = 'LOADING';
const ADD_TO_SHOPPING_CARD = 'ADD_TO_SHOPPING_CARD';
const CHANGE_QUANTITY = 'CHANGE_QUANTITY';

export default {
  GET_PRODUCT,
  ADD_PRODUCTS,
  LOADING,
  ADD_TO_SHOPPING_CARD,
  CHANGE_QUANTITY,
};
